### PR TITLE
immursive erp code

### PR DESCRIPTION
**Pull request by LetterN**
/mob/var/more_lewd_erp = FALSE //tell admins if you want to erp, set this to 1

### CODE REVIEW

**Comment by Kmc2000** [comment]
youre a fucking god

**Comment by Kmc2000** [comment]
https://www.youtube.com/watch?v=j4CqLI5WfWY

**Comment by ghost** [comment]
yeah fuck you @HONKERTRON fuck atmta station and most importantly fuck me
fuck me harder daddy

**Comment by mattmatterson111** [comment]
Wow this bunkerstation levels of old. Smell that fresh 2016 air mm, mm.

**Pull request merged**
